"""profile_actions_notes

Revision ID: 2ffb7aba9c96
Revises: d66c21aaa280
Create Date: 2024-06-25 12:36:23.627666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ffb7aba9c96'
down_revision = 'd66c21aaa280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_actions', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
