"""profile_actions

Revision ID: 3268ddf05f6c
Revises: 376ca0883102
Create Date: 2024-06-25 02:13:01.214074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3268ddf05f6c'
down_revision = '376ca0883102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_actions', schema=None) as batch_op:
        batch_op.drop_column('association_datetime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('association_datetime', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
