"""code

Revision ID: 376ca0883102
Revises: 4d2c5786168d
Create Date: 2024-06-25 00:59:57.561786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '376ca0883102'
down_revision = '4d2c5786168d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_index('code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index('code', ['code'], unique=True)
        batch_op.alter_column('code',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
