"""creator

Revision ID: 4d2c5786168d
Revises: 2f5f429b24f2
Create Date: 2024-06-24 21:52:40.313740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d2c5786168d'
down_revision = '2f5f429b24f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('creation_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('creation_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_actions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('creation_time')
        batch_op.drop_column('creation_date')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
