"""profiles

Revision ID: 650c9e79a3eb
Revises: 2ffb7aba9c96
Create Date: 2024-06-26 23:42:13.731714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650c9e79a3eb'
down_revision = '2ffb7aba9c96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('est_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('account_manager', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('account_manager_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phones', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('phones')
        batch_op.drop_column('account_manager_email')
        batch_op.drop_column('account_manager')
        batch_op.drop_column('est_date')

    # ### end Alembic commands ###
