"""profile_actions2

Revision ID: d38ad9c7560f
Revises: bdad7b157c68
Create Date: 2024-06-25 03:05:48.926386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd38ad9c7560f'
down_revision = 'bdad7b157c68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_actions', schema=None) as batch_op:
        batch_op.drop_constraint('profile_actions_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('profile_actions_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('profile_actions_ibfk_1', type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('profile_id')
        batch_op.drop_column('action_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('profile_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('profile_actions_ibfk_1', 'actions', ['action_id'], ['id'])
        batch_op.create_foreign_key('profile_actions_ibfk_2', 'profiles', ['profile_id'], ['id'])
        batch_op.create_foreign_key('profile_actions_ibfk_3', 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###
